tasks:
  - name: install railway
    before: npm i -g @railway/cli

vscode:
  extensions:
    - swellaby.rust-pack
    - karunamurti.tera
    - ms-azuretools.vscode-docker

ports:
  - port: 8000
    onOpen: open-preview
