tasks:
  - name: install railway
    command: npm i -g @railway/cli

  - name: set rust default
    command: rustup default nightly

vscode:
  extensions:
    - swellaby.rust-pack
    - karunamurti.tera
    - ms-azuretools.vscode-docker

ports:
  - port: 8000
    onOpen: open-preview
