tasks:
  - name: install railway
    command: npm i -g @railway/cli

  - name: set rust default
    command: rustup default nightly

  - name: install rust tools
    command: rustup component add rust-analysis rust-src rls clippy

vscode:
  extensions:
    - swellaby.rust-pack
    - karunamurti.tera
    - ms-azuretools.vscode-docker

ports:
  - port: 8000
    onOpen: open-preview
