// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mastodon} from '../models';

export function FetchPosts():Promise<Array<mastodon.Status>>;
